function scenario = openScenarioInApp()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.9 (R2020b) and Automated Driving Toolbox 3.2 (R2020b).
% Generated on: 27-Mar-2021 18:39:07

%% Add all road segments
scenario = scenario_map_v1(); % export from drivingScenarioDesigner

%% Add all the Vehicles as actors and their trajectory data to the drivingSceanario object
load('vehicleTrajectories.mat'); % TODO: the .mat file should be renamed to vehicleTrajectories.mat
step_length = 10; % Affects how fine the trajectory waypoint sampling is.


%if you want to change the ego vehicle, just put the code of the corresponding vehicle to the first place.
car2 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-V2_translation.Data(1,3) -V2_translation.Data(1,1) 0]);
    waypoints = [-V2_translation.Data((1:step_length:end),3) -V2_translation.Data((1:step_length:end),1) V2_translation.Data((1:step_length:end),2)];
    speed = V2_speed.Data(1:step_length:end);
    trajectory(car2, waypoints, speed);

    % Add the non-ego actors
car1 = vehicle(scenario, ...
     'ClassID', 1, ...
     'Position', [-V1_translation.Data(1,3) -V1_translation.Data(1,1) 0]);
     waypoints = [-V1_translation.Data((1:step_length:end),3) -V1_translation.Data((1:step_length:end),1) V1_translation.Data((1:step_length:end),2)];
     speed = V1_speed.Data(1:step_length:end);
     trajectory(car1, waypoints, speed);
    
car3 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-V3_translation.Data(1,3) -V3_translation.Data(1,1) 0]);
    waypoints = [-V3_translation.Data((1:step_length:end),3) -V3_translation.Data((1:step_length:end),1) V3_translation.Data((1:step_length:end),2)];
    speed = V3_speed.Data(1:step_length:end);
    trajectory(car3, waypoints, speed);
    
car4 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-V4_translation.Data(1,3) -V4_translation.Data(1,1) 0]);
    waypoints = [-V4_translation.Data((1:step_length:end),3) -V4_translation.Data((1:step_length:end),1) V4_translation.Data((1:step_length:end),2)];
    speed = V4_speed.Data(1:step_length:end);
    trajectory(car4, waypoints, speed);
    
car5 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-V5_translation.Data(1,3) -V5_translation.Data(1,1) 0]);
    waypoints = [-V5_translation.Data((1:step_length:end),3) -V5_translation.Data((1:step_length:end),1) V5_translation.Data((1:step_length:end),2)];
    speed = V5_speed.Data(1:step_length:end);
    trajectory(car5, waypoints, speed);
    
 car6 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-V6_translation.Data(1,3) -V6_translation.Data(1,1) 0]);
    waypoints = [-V6_translation.Data((1:step_length:end),3) -V6_translation.Data((1:step_length:end),1) V6_translation.Data((1:step_length:end),2)];
    speed = V6_speed.Data(1:step_length:end);
    trajectory(car6, waypoints, speed);
    
 car7 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-V7_translation.Data(1,3) -V7_translation.Data(1,1) 0]);
    waypoints = [-V7_translation.Data((1:step_length:end),3) -V7_translation.Data((1:step_length:end),1) V7_translation.Data((1:step_length:end),2)];
    speed = V7_speed.Data(1:step_length:end);
    trajectory(car7, waypoints, speed);
    
 car8 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-V8_translation.Data(1,3) -V8_translation.Data(1,1) 0]);
    waypoints = [-V8_translation.Data((1:step_length:end),3) -V8_translation.Data((1:step_length:end),1) V8_translation.Data((1:step_length:end),2)];
    speed = V8_speed.Data(1:step_length:end);
    trajectory(car8, waypoints, speed);
    
car9 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-V9_translation.Data(1,3) -V9_translation.Data(1,1) 0]);
    waypoints = [-V9_translation.Data((1:step_length:end),3) -V9_translation.Data((1:step_length:end),1) V9_translation.Data((1:step_length:end),2)];
    speed = V9_speed.Data(1:step_length:end);
    trajectory(car9, waypoints, speed);
    
car10 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-V10_translation.Data(1,3) -V10_translation.Data(1,1) 0]);
    waypoints = [-V10_translation.Data((1:step_length:end),3) -V10_translation.Data((1:step_length:end),1) V10_translation.Data((1:step_length:end),2)];
    speed = V10_speed.Data(1:step_length:end);
    trajectory(car10, waypoints, speed);
    
    %% Open the scenario in drivingScenarioDesigner (This way it can be also edited or simulated 3D in Unreal Engine)
    drivingScenarioDesigner(scenario)

