function Vehicles = load_vehicles(startingPoints, destinationPoints, maxSpeeds, startingTimes, simSpeed)

    VehicleNames = [{'V1 - Sally Carrera'} ...
                    {'V2 - Lightning McQueen'} ...
                    {'V3 - Luigi'} ...
                    {'V4 - Chick Hicks'} ...
                    {'V5 - Doc Hudson'} ...
                    {'V6 - Red'} ...
                    {'V7 - Fillmore'} ...
                    {'V8 - Guido'} ...
                    {'V9 - Mater'} ...
                    {'V10 - Sheriff'}];
    nrVehicles = length(VehicleNames);
    
    % According to the Cuboid world standard vehicle dimensions [2 1.8 4.7] => [height, width, length] in meters
    sizes = [[2 1.8 4.7];[2 1.8 4.7];[2 1.8 4.7];[2 1.8 4.7]; [2 1.8 4.7]; [2 1.8 4.7]; [2 1.8 4.7]; [2 1.8 4.7]; [2 1.8 4.7]; [2 1.8 4.7]];
    mass = [1800,3000,900,3000,900, 900,1000,1000,1000,1000];
    dataLinksV2V = ones(nrVehicles,nrVehicles);
    dataLinksV2I = ones(1,nrVehicles);


    frontSensorRange = 100.* ones(1,nrVehicles);
    AEBdistance = 25.* ones(1,nrVehicles);
    minDeceleration = -9.15.* ones(1,nrVehicles); % -9.15 m/s^2 dec

    Vehicles = [];
    for j=1:nrVehicles
        % Generate vehicle
        NewVehicle = Vehicle(j,VehicleNames{j},startingPoints(j),destinationPoints(j),...
        startingTimes(j),maxSpeeds(j),sizes(j,:),dataLinksV2V(j,:),dataLinksV2I(j),mass(j),...
        simSpeed,frontSensorRange(j),AEBdistance(j),minDeceleration(j));
    
        % Add to vehicle array
        Vehicles = [Vehicles NewVehicle];
    end
end