function scenario = exported_map_v1()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.9 (R2020b) and Automated Driving Toolbox 3.2 (R2020b).
% Generated on: 15-Aug-2021 14:35:08

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [0 0 0;
    -50 0 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '40');

roadCenters = [-90 40 0;
    -90 140 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '41');

roadCenters = [-78 168 0;
    -8 239 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '42');

roadCenters = [-90 140 0;
    -90 220 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '43');

roadCenters = [-150 280 0;
    -250 280 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '44');

roadCenters = [-300 230 0;
    -300 160 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '45');

roadCenters = [-250 110 0;
    -170 110 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '46');

roadCenters = [-250 280 0;
    -390 280 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road7');

roadCenters = [-480 370 0;
    -480 190 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road8');

roadCenters = [-480 190 0;
    -480 40 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road9');

roadCenters = [-480 40 0;
    -480 -40 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road10');

roadCenters = [-480 -40 0;
    -480 -120 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road11');

roadCenters = [-410 -190 0;
    -310 -190 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road12');

roadCenters = [-250 -250 0;
    -250 -320 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road13');

roadCenters = [-200 -370 0;
    -130 -370 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road14');

roadCenters = [-90 -330 0;
    -90 -170 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road15');

roadCenters = [-90 -170 0;
    -90 40 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road16');

roadCenters = [-250 -320 0;
    -250 -420 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road17');

roadCenters = [-300 -470 0;
    -350 -470 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road18');

roadCenters = [-300 160 0;
    -300 80 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road19');

roadCenters = [-320 60 0;
    -460 60 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road20');

roadCenters = [-170 110 0;
    -120 110 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road21');

roadCenters = [-140 80 0;
    -140 -20 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road22');

roadCenters = [-170 -50 0;
    -210 -50 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road23');

roadCenters = [-140 -20 0;
    -140 -180 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road24');

roadCenters = [-170 -210 0;
    -210 -210 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road25');

roadCenters = [-130 -370 0;
    50 -370 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road26');

roadCenters = [100 -220 0;
    100 -120 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road27');

roadCenters = [100 -320 0;
    100 -220 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road28');

roadCenters = [300 80 0;
    300 200 0];
laneSpecification = lanespec(2, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road29');

roadCenters = [100 140 0;
    100 240 0];
laneSpecification = lanespec(1);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road30');

roadCenters = [100 -120 0;
    100 140 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road31');

roadCenters = [240 -370 0;
    370 -370 0];
laneSpecification = lanespec(1);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road32');

roadCenters = [140 -370 0;
    240 -370 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road33');

roadCenters = [50 -370 0;
    140 -370 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road34');

roadCenters = [370 -170 0;
    230 -170 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road35');

roadCenters = [300 -100 0;
    300 80 0];
laneSpecification = lanespec(2, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road36');

roadCenters = [450 200 0;
    450 -90 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road37');

roadCenters = [120 50 0;
    120 -20 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road38');

roadCenters = [120 340 0;
    120 240 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road39');

roadCenters = [120 530 0;
    120 340 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road40');

roadCenters = [100 240 0;
    100 340 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road41');

roadCenters = [-250 300 0;
    60 300 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road42');

roadCenters = [60 300 0;
    160 300 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road43');

roadCenters = [160 280 0;
    60 280 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road44');

roadCenters = [260 300 0;
    350 300 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road45');

roadCenters = [220 280 0;
    160 280 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road46');

roadCenters = [160 300 0;
    260 300 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road47');

roadCenters = [-130 280 0;
    -150 280 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road48');

roadCenters = [-30 280 0;
    -130 280 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road49');

roadCenters = [60 280 0;
    -30 280 0];
laneSpecification = lanespec(1);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road50');

roadCenters = [100 440 0;
    100 530 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road51');

roadCenters = [100 340 0;
    100 440 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road52');

roadCenters = [120 140 0;
    120 50 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road53');

roadCenters = [120 240 0;
    120 140 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road54');

roadCenters = [-50 0 0;
    -60.353 1.363 0;
    -70 5.359 0;
    -78.284 11.716 0;
    -84.641 20 0;
    -88.637 29.647 0;
    -90 40 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road55');

roadCenters = [-90 140 0;
    -88.5172 151.4 0;
    -84.4235 159.833 0;
    -78 168 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road56');

roadCenters = [-90 220 0;
    -92.0445 235.529 0;
    -98.0385 250 0;
    -107.574 262.426 0;
    -120 271.962 0;
    -134.471 277.955 0;
    -150 280 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road57');

roadCenters = [-250 280 0;
    -262.941 278.296 0;
    -275 273.301 0;
    -285.355 265.355 0;
    -293.303 255 0;
    -298.296 242.941 0;
    -300 230 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road58');

roadCenters = [-300 160 0;
    -298.296 147.059 0;
    -293.303 135 0;
    -285.353 124.645 0;
    -275 116.699 0;
    -262.941 111.704 0;
    -250 110 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road59');

roadCenters = [-390 280 0;
    -413.294 276.933 0;
    -435 267.942 0;
    -453.64 253.65 0;
    -467.942 235 0;
    -476.933 213.294 0;
    -480 190 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road60');

roadCenters = [-480 -120 0;
    -477.625 -138.117 0;
    -470.622 -155 0;
    -459.498 -169.498 0;
    -445 -180.622 0;
    -428.117 -187.615 0;
    -410 -190 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road61');

roadCenters = [-310 -190 0;
    -290.2 -193.5 0;
    -280 -198.038 0;
    -267.574 -207.574 0;
    -258.038 -220 0;
    -252.044 -234.471 0;
    -250 -250 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road62');

roadCenters = [-250 -320 0;
    -247 -335.1 0;
    -243.301 -345 0;
    -235.355 -355.355 0;
    -225 -363.301 0;
    -212.941 -368.296 0;
    -200 -370 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road63');

roadCenters = [-130 -370 0;
    -119.647 -368.637 0;
    -110 -364.641 0;
    -101.716 -358.284 0;
    -95 -350 0;
    -91 -340.353 0;
    -90 -330 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road64');

roadCenters = [-250 -420 0;
    -251.704 -432.941 0;
    -256.699 -445 0;
    -264.645 -455.355 0;
    -275 -463.301 0;
    -287.059 -468.296 0;
    -300 -470 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road65');

roadCenters = [-300 80 0;
    -300.682 74.92 0;
    -302.68 70 0;
    -305.858 65.8579 0;
    -310 62.6795 0;
    -314.824 60.6815 0;
    -320 60 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road66');

roadCenters = [-460 60 0;
    -465.176 59.3185 0;
    -470 57.3205 0;
    -474.142 54.1421 0;
    -477.32 50 0;
    -479.318 45.38 0;
    -480 40 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road67');

roadCenters = [-170 110 0;
    -162.235 108.978 0;
    -155 105.981 0;
    -148.787 101.213 0;
    -144.35 95 0;
    -141.022 87.7646 0;
    -140 80 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road68');

roadCenters = [-120 110 0;
    -112.235 111.022 0;
    -105 114.019 0;
    -98.7868 118.787 0;
    -94.0192 125 0;
    -91.0222 132.235 0;
    -90 140 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road69');

roadCenters = [-140 -20 0;
    -141.022 -27.7646 0;
    -144.019 -35 0;
    -148.787 -41.2132 0;
    -155 -45.9808 0;
    -162.235 -48.9778 0;
    -170 -50 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road70');

roadCenters = [-140 -180 0;
    -141.022 -187.765 0;
    -144.019 -195 0;
    -148.787 -201.213 0;
    -155 -205.981 0;
    -162.235 -208.978 0;
    -170 -210 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road71');

roadCenters = [-210 -210 0;
    -220.353 -211.363 0;
    -230 -215.359 0;
    -238.284 -221.716 0;
    -244.641 -230 0;
    -248.637 -239.647 0;
    -250 -250 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road72');

roadCenters = [50 -370 0;
    62.9401 -368.296 0;
    75 -363.301 0;
    85.3553 -355.355 0;
    93.3013 -345 0;
    98.2963 -332.941 0;
    100 -320 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road73');

roadCenters = [100 -120 0;
    102.044 -104.471 0;
    108.038 -90 0;
    117.574 -77.5736 0;
    130 -68.0385 0;
    144.471 -62.3 0;
    160 -60 0];
marking = [laneMarking('Solid', 'Color', [0.98 0.86 0.36])
    laneMarking('Dashed')];
laneSpecification = lanespec(1, 'Width', 3.7, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road74');

roadCenters = [160 -60 0;
    196.235 -55.2296 0;
    230 -41.2436 0;
    258.995 -18.9949 0;
    281.244 10 0;
    295.23 43.7653 0;
    300 80 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road75');

roadCenters = [300 200 0;
    297.274 220.706 0;
    289.282 240 0;
    276.568 256.568 0;
    260 269.282 0;
    240.706 277.274 0;
    220 280 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road76');

roadCenters = [370 -370 0;
    395.882 -366.593 0;
    420 -356.603 0;
    440.711 -340.711 0;
    456.603 -320 0;
    466.593 -295.882 0;
    470 -270 0;
    466.593 -244.118 0;
    456.603 -220 0;
    440.711 -199.289 0;
    420 -183.398 0;
    395.882 -173.407 0;
    370 -170 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road77');

roadCenters = [370 -170 0;
    351.883 -167.615 0;
    335 -160.622 0;
    320.502 -149.498 0;
    309.378 -135 0;
    302.385 -118.117 0;
    300 -100 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road78');

roadCenters = [-250 280 0;
    -257.07 282.93 0;
    -260 290 0;
    -257.07 297.07 0;
    -250 300 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road79');

roadCenters = [350 300 0;
    375.882 296.593 0;
    400 286.603 0;
    420.711 270.711 0;
    436.603 250 0;
    446.593 225.882 0;
    450 200 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road80');

roadCenters = [450 -90 0;
    447.274 -110.706 0;
    439.282 -130 0;
    426.568 -146.569 0;
    410 -159.28 0;
    390.705 -167.274 0;
    370 -170 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road81');

roadCenters = [380 120 0;
    359.295 122.726 0;
    340 130.718 0;
    323.432 143.431 0;
    310.718 160 0;
    302.726 179.294 0;
    300 200 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road82');

roadCenters = [24 -305 0;
    42.3564 -284.48 0;
    56.247 -265.512 0;
    69.6112 -243.069 0;
    80.6681 -219.405 0;
    89.3073 -194.754 0;
    94.9435 -171.93 0;
    98.7717 -146.091 0;
    100 -120 0];
marking = [laneMarking('Solid', 'Color', [0.98 0.86 0.36])
    laneMarking('Dashed')];
laneSpecification = lanespec(1, 'Width', 3.7, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road83');

roadCenters = [120 -20 0;
    121.363 -30.3528 0;
    125.359 -40 0;
    131.716 -48.2843 0;
    140 -54.641 0;
    149.647 -59.2 0;
    160 -60 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road84');

roadCenters = [100 530 0;
    100.757 533.817 0;
    102.902 537.044 0;
    106.206 539.252 0;
    110.008 540 0;
    113.809 539.246 0;
    117.038 537.104 0;
    119.249 533.802 0;
    120 530 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road85');

roadCenters = [160 280 0;
    149.693 278.649 0;
    140.104 274.701 0;
    131.851 268.419 0;
    125.291 259.882 0;
    121.346 250.29 0;
    120 240 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road86');

roadCenters = [100 240 0;
    102.029 255.471 0;
    107.955 269.854 0;
    117.379 282.231 0;
    130.187 292.069 0;
    144.575 297.983 0;
    160 300 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road87');

roadCenters = [120 340 0;
    121.351 329.693 0;
    125.299 320.104 0;
    131.581 311.851 0;
    140.118 305.291 0;
    149.71 301.346 0;
    160 300 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road88');

roadCenters = [160 280 0;
    144.518 282.032 0;
    130.136 287.96 0;
    117.761 297.387 0;
    107.925 310.197 0;
    102.014 324.586 0;
    100 340 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road89');

roadCenters = [60 300 0;
    70.314 301.353 0;
    79.9028 305.303 0;
    88.1538 311.586 0;
    94.7128 320.125 0;
    98.6556 329.717 0;
    100 340 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road90');

roadCenters = [120 340 0;
    117.971 324.529 0;
    112.045 310.146 0;
    102.621 297.769 0;
    89.8128 287.931 0;
    75.4248 282.017 0;
    60 280 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road91');

roadCenters = [100 240 0;
    98.6474 250.314 0;
    94.6969 259.903 0;
    88.4141 268.154 0;
    79.8752 274.713 0;
    70.2832 278.656 0;
    60 280 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road92');

roadCenters = [60 300 0;
    75.471 297.971 0;
    89.8543 292.045 0;
    102.231 282.621 0;
    112.069 269.813 0;
    117.983 255.425 0;
    120 240 0];
laneSpecification = lanespec(1, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road93');

roadCenters = [370 -370 0;
    380 -372.68 0;
    387.32 -380 0;
    390 -390 0;
    388.79 -396.84 0;
    387.32 -400 0];
laneSpecification = lanespec(2, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

roadCenters = [387.32 -400 0;
    320 -516.6 0];
laneSpecification = lanespec(2, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road1');

roadCenters = [320 -516.6 0;
    314.864 -523.22 0;
    308.126 -528.2 0;
    300.29 -531.166 0;
    291.943 -531.898 0;
    283.711 -530.336 0;
    276.209 -526.606 0;
    270 -520.98 0];
laneSpecification = lanespec(2, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road2');

roadCenters = [270 -520.98 0;
    264.104 -515.576 0;
    257.011 -511.883 0;
    249.203 -510.151 0;
    241.213 -510.499 0;
    233.585 -512.904 0;
    226.84 -517.2 0];
laneSpecification = lanespec(2, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road3');

roadCenters = [226.84 -517.2 0;
    208.93 -530.406 0;
    189.777 -541.137 0;
    167.365 -550.107 0;
    147.953 -555.189 0;
    125.672 -558.239 0;
    103.956 -558.486 0;
    81.4942 -555.923 0;
    60.505 -550.824 0;
    39.2626 -542.749 0;
    20.2884 -532.678 0;
    1.6032 -519.536 0;
    -14.2067 -505.169 0;
    -29.1425 -487.728 0;
    -40.85 -470 0];
laneSpecification = lanespec(2, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road4');

roadCenters = [-40.85 -470 0;
    -46.7094 -462.365 0;
    -54.3448 -456.507 0;
    -63.2361 -452.824 0;
    -72.77 -451.57 0;
    -82.3191 -452.823 0;
    -91.2109 -456.505 0;
    -98.8471 -462.362 0;
    -104.7 -470 0];
laneSpecification = lanespec(2, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road5');

roadCenters = [-104.7 -470 0;
    -110.558 -477.636 0;
    -118.194 -483.496 0;
    -136.627 -488.437 0;
    -155.062 -483.499 0;
    -162.698 -477.64 0;
    -168.55 -470 0];
laneSpecification = lanespec(2, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road6');

roadCenters = [-168.55 -470 0;
    -174.735 -462.043 0;
    -182.844 -456.059 0;
    -192.271 -452.495 0;
    -202.31 -451.617 0;
    -212.212 -453.492 0;
    -221.237 -457.978 0;
    -228.71 -464.74 0];
laneSpecification = lanespec(2, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road94');

roadCenters = [-228.71 -464.74 0;
    -233.77 -468.62 0;
    -240 -470 0];
laneSpecification = lanespec(2, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road95');

roadCenters = [-240 -470 0;
    -300 -470 0];
laneSpecification = lanespec(2, 'Width', 3.7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road96');

